language: python
python:
  - "3.7"

services:
  - docker

before_script: pip install docker-compose

script:
  - sudo docker-compose run ccvalidate sh -c "coverage run --source='.' manage.py test && flake8"
after_success:
  - coveralls