version: "3"

services:
  ccvalidate:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./ccvalidate:/ccvalidate
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=api
      - DB_USER=postgres
      - DB_PASS=postgrespassword
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespassword